stages:
  - build

.build_template:
  stage: build
  image:
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]
  variables:
    DOCKERFILE: Docker/Dockerfile
    TAG: master
    DESTINATION: "${CI_REGISTRY_IMAGE}:${TAG}"
  before_script:
    - mkdir -p /kaniko/.docker
    - |
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
script:
    - echo "CI_PROJECT_DIR=$CI_PROJECT_DIR"
    - pwd
    - ls -la
    - ls -la "$CI_PROJECT_DIR"
    - ls -la "$CI_PROJECT_DIR/Docker"
    - /kaniko/executor \
        --context "dir://${CI_PROJECT_DIR}" \
        --dockerfile "${CI_PROJECT_DIR}/Docker/Dockerfile" \
        --destination "${DESTINATION}" \
        --force
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

build-image:
  extends: .build_template